feat: Implements queuring full voice channels
cglotr/anasbot pull request #12
Opened 2020-11-18 15:45 UTC by hbina

(Garbage) implementation of this feature.
Still trying to figure out how to do this sanely

See #7

Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>

2020-11-21 03:06 UTC, cglotr requested changes

2020-11-21 03:06 UTC, cglotr commented on src/managers/roommanagerimpl.ts
> +    this.userQueue.push({ user, channel });
This will be potentially contain duplicates?

2020-11-21 03:06 UTC, cglotr commented on src/types/channelqueue.ts
> +  user: Discord.User;
I think better to only store the user id & fetch it on demand when we want to.

2020-11-21 03:06 UTC, cglotr commented on src/main.ts
> +    roomManager.workOnQueues();
I think we should move this to a cron process.

2020-11-21 03:06 UTC, cglotr commented on src/managers/roommanagerimpl.ts
> +    const nextQueue: ChannelQueue[] = [];
Should we have `n` number of queues, one for each tracked room?

2020-11-21 14:07 UTC, hbina commented
@cglotr applied the requested changes. The only thing left is prolly checking edge cases and adding unit tests.

2020-11-21 14:09 UTC, hbina commented on src/managers/queuemanagerimpl.test.ts
> +import { DiscordGuild } from '../discord/discordguild';
This is the _wrong_ test.

2020-11-29 04:22 UTC, cglotr approved these changes

2020-11-29 04:22 UTC, merged